apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-12-29T08:16:49Z"
  generation: 1
  labels:
    app: rabbitmq-management
  name: rabbitmq-management
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rabbitmq-management
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbitmq-management
    spec:
      containers:
        - image: rabbitmq:management
          imagePullPolicy: IfNotPresent
          name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-management
  name: rabbitmq-management
spec:
  ports:
    - name: hhh
      nodePort: 31472
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31672
  selector:
    app: rabbitmq-management
  type: LoadBalancer